### ISSUE TITLE
Thoughts on 2022 Day 24

### ISSUE THREAD

**Issue by dk5ax** [KittyGiraudel/aoc#11]
Your solution is nicely coded, however I think that there might be some things that would make it far easier.
My approach was a "simple" BFS, given 2 additions:
1. The "visited" cache contains a visited position and time % COLUMNS and time % ROWS additionally. A state is to be considered as seen before in case the blizaards are aligned as the have been the last time. In case the blizzards are not equally positioned (horizontally AND vertically) that is a different state.
2. I only calculated
```Javascript
function isBlizzard_at_t(y,x,t)
```
to allow filtering for possitble states:
```Javascript
let possiblepos = aroundpos.filter(p => !isBlizzard_at_t(p[0], p[1], state.t + 1) 
            && !visited.has([p[0], p[1], (state.t + 1) % COLUMNS, (state.t + 1) % ROWS].join('_')
```

Just my 2 cents! Thanks for sharing your code and especially the helpers that I "borrowed" partially. Have a nice XMAS!
            ));

**Comment by KittyGiraudel** [comment]
Hellooo! ✨  Thank you for sharing your thoughts! Truth be told, BFS/DFS exercises are typically not my cup of tea. I’m a frontend engineer at heart and do not have a CS degree, so it’s not exactly the kind of logic that comes naturally to me. I usually dread the days that are pathfinding related. 😅
