### ISSUE TITLE
Optimization of intersection.js in helpers

### ISSUE THREAD

**Issue by dk5ax** [KittyGiraudel/aoc#8]
I think that there is an optimization in the intersection helper possible:
I think it is not required to have the outer loop as just one array has to be considered (and each of its elements has to be checked to be included in the other array). So what do you think about this?

```js
/** Return the intersections of several arrays.
 * @param {Array[]} arrays - Arrays to find the intersection of
 * @return {Array}
 */
const intersection = (...arrays) => {
    const result = new Set();
    if (arrays.length < 2) return [];
    const a0 = arrays[0];
    arrays = arrays.slice(1);
  
    for (let y = 0; y < a0.length; y++) {
        if (arrays.every(obj => obj.includes(a0[y])))
            result.add(a0[y]);
    }  
    return [...result]
  }
  
  module.exports = intersection
```

**Comment by KittyGiraudel** [comment]
Hello! 

Correct me if I’m wrong, but we would still have two loops, except instead of two `for` loops, we’d have a `for` loop and an `.every()` loop. I think the performance benefit from your version is that `.every()` will eject early if it finds an array without the entry, so that may matter on large sets. But we still have 2 loops, so ultimately it’s not going to be _that_ much faster?

(Simplified your code a bit as well, if you’d like to see:)
```js
const intersection = (...arrays) => {
  const result = new Set()

  if (arrays.length <= 1) return []

  const first = arrays.shift()

  for (let i = 0; i < first.length; i++) {
    const item = first[i]

    if (arrays.every(array => array.includes(item))) result.add(item)
  }

  return [...result]
}
```

**Comment by dk5ax** [comment]
Hello, I think it is a difference as the initial code tries to loop over all(!) arrays and that it is impossible that some element that had not been added by looping  the first array's members could ever become part of the result anyways. Nice discussion!
However, nice side note: i applied this in this year's day 3

```Javascript
// Advent of Code 2022 Day 3 Part 1

const TRAINING = false;
// const TRAINING = true;
const fs = require("fs");
const AoC = require ('../../lib');

let inputfilename = (TRAINING) ? __dirname +"\\input_training.txt" : __dirname +"\\input.txt";
let input = fs.readFileSync(inputfilename, "utf-8").split('\r\n')

let rucksacks = input.map(l => {
    let r1 = l.slice(0,l.length/2);
    let r2 = l.slice(l.length/2);
    // console.log(r1.length, r2.length);
    return [r1,r2]
})
console.log(rucksacks);

let part1 = 0;
rucksacks.forEach(l => {
    c1 = l[0].split('');
    c2 = l[1].split('');
    let r = AoC.intersection(c1,c2)[0];
    let v = (r.charCodeAt(0) > 96) ? r.charCodeAt(0) - 96 : r.charCodeAt(0) - 38;
    part1 += v
});
console.log(`Part 1: ${part1}`);
```

**Comment by KittyGiraudel** [comment]
Done with https://github.com/KittyGiraudel/aoc/commit/10376f580407e7295747ccf6eeeb6f2cf52b9554.

**Comment by KittyGiraudel** [comment]
I’m thinking this is an even shorter version:

```js
const intersection = (...arrays) =>
  arrays.shift().filter(item => arrays.every(array => array.includes(item)))
```

**Comment by dk5ax** [comment]
This is great! Many thanks! Enjoy AoC 2022!
